import Head from "next/head";
import React from "react";
import { Footer } from "./Footer";
import { Header } from "./Header";
import { ThemeProvider } from "./ThemeProvider";

interface Props extends React.PropsWithChildren<{}> {
  subTitle?: string;
}

export type { Props as BasicLayoutProps };

export const BASE_TITLE = "Next Blog";

export const BasicLayout: React.FC<Props> = ({ subTitle, children }) => {
  return (
    <>
      <Head>
        <title>{subTitle ? `${BASE_TITLE} - ${subTitle}` : BASE_TITLE}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          <div className="content">{children}</div>
          <Footer />
        </ThemeProvider>
      </main>
    </>
  );
};
